Support not-strict macros
cel-expr/cel-go pull request #119
Opened 2018-11-30 21:13 UTC by TristonianJones

#43 Introduce the `not_strictly_false` macro to ensure that the `all` and `exists` macros
accumulate in the same manner as the `||` and `&&` operators would if the macro loops
were unrolled.

*  A new non-strict logical primitive `not_strictly_false` is added that returns
    its argument or true if the argument has an error or is unknown.
*  The macro expansion for ALL and EXISTS uses the  new `not_strictly_false` primitive
    to effectively make the termination condition non-strict as well in these cases.
    In other cases where the comprehension step is naturally strict, the termination
    condition remains strict as well.

During the development of this code an off-by-one error was revealed in the `astwalker.go`
which could cause the program to terminate without moving the final evaluation to the
result register.

2018-12-01 01:36 UTC, JimLarson commented on common/operators/operators.go
> +	NotStrictlyFalse = "__not_strictly_false__"
Add gratuitous punctuation to make it an invalid identifier.

2018-12-01 01:36 UTC, JimLarson commented on interpreter/astwalker.go
> +	// 6: iterVar = it.next()             # it.next()
x = it.next()?  or change step 9 to be accu = accu && iterVar < 10?

2018-12-01 01:36 UTC, JimLarson commented on interpreter/astwalker.go
> +	// 7: loop = eval(accu, iterVar)      # loopCondition
Wot?  Isn't the loop condition just accu?

2018-12-01 01:36 UTC, JimLarson commented on interpreter/functions/standard.go
> +		// Not strictly false: IsBool(a) ? true : true
Shouldn't this be IsBool(a) ? a : true

2018-12-01 01:36 UTC, JimLarson commented on interpreter/interpreter_test.go
> +}
You're using this pattern enough that it seems to be worth abstracting:

func TestInterpreter_Blah(t *testing.T) {
        EvalExpectingTrue("[0, 2, 4].exists(x, whatever(x))")
}

2018-12-01 01:36 UTC, JimLarson commented on interpreter/prune_test.go
> +				test.ExprLiteral(9, false),
Make a note saying where expr 8 went.

2018-12-04 00:01 UTC, TristonianJones commented on interpreter/interpreter_test.go
> +}
Go sort of frowns on assertion helpers, but since the evaluation of the source and errors related to it are just a general part of test setup, I've moved them into a helper function called `evalExpr`

2018-12-04 00:01 UTC, TristonianJones commented on interpreter/prune_test.go
> +				test.ExprLiteral(9, false),
Just missed it is all. :)

2018-12-04 00:02 UTC, TristonianJones commented on common/operators/operators.go
> +	NotStrictlyFalse = "__not_strictly_false__"
Unfortunately, I can't change this one since it's referenced in other contexts by this identifier.

2018-12-05 00:40 UTC, JimLarson requested changes

2018-12-05 00:40 UTC, JimLarson commented on common/operators/operators.go
> +	NotStrictlyFalse = "__not_strictly_false__"
Add an alias so that the other contexts can switch.

2018-12-05 17:25 UTC, TristonianJones commented on common/operators/operators.go
> +	NotStrictlyFalse = "__not_strictly_false__"
I've made a shift to `@<internal_operator_name>` and preserved the aliases to the old functions in the `interpreter`. Please take another look.

2018-12-05 18:32 UTC, JimLarson approved these changes

2018-12-05 18:37 UTC, merged