High level interface definition for CEL
cel-expr/cel-go pull request #148
Opened 2019-01-11 22:07 UTC by TristonianJones

This is a first pass at creating a new high-level interface for CEL.

Core changes:

* `Env` vs. `Program`
  * `Env` is static and used for compiling many expressions.
  * `Program` is the executable view of a compiled AST.
* Functional options to configure the `Env`, `Program`, and per-execution `Eval`.
* `EvalFlag` used to optimize the memory use and evaluation behavior.
* `Issues` are now returned from the `Parse` and `Check` calls to support the future
   introduction of non-fatal messages from expression compilation phases.

While the changes do not completely insulate the use of CEL from it's backing
protocol buffer types for expressions, they vastly reduce the surface area of the
library. Future improvements will try to reduce the friction and import set required
to use CEL.

Closes #126, #130

2019-01-24 22:43 UTC, JimLarson reviewed
Checkpointing my comments.

2019-01-24 22:43 UTC, JimLarson commented on README.md
> +	p, _ := env.Parse(`"Hello " + you + "! I'm " + i + "."`)
Here and below, include proper checks of the result of each phase.  Yes, a little more wordy, but makes the example a lot more useful for real code.

2019-01-24 22:43 UTC, JimLarson commented on cel/BUILD.bazel
> +)
Missing newline at EOF.

2019-01-24 22:43 UTC, JimLarson commented on cel/cel_test.go
> +	p, _ := e.Parse("i.greet(you)")
Especially in the example, illustrate error handling, here and below.

2019-01-24 22:43 UTC, JimLarson commented on cel/io.go
> +// CheckedExprToAst converts a checked expression proto message to an Ast.
Please implement the inverse too, and for ParsedExpr as well.

2019-01-24 22:43 UTC, JimLarson commented on cel/options.go
> +// DisableBuiltIns option removes all standard operators from the environment.
Also repeat the note from Declarations:  if also using Declarations(), those must come after.

2019-01-24 22:43 UTC, JimLarson commented on cel/options.go
> +type EnvOption func(e *env) (*env, error)
Do you foresee returning a different *env than the one you were given?

2019-01-24 22:43 UTC, JimLarson commented on cel/env.go
> +	IsChecked() bool
Consider putting the docstring on the interface methods and have the implementations reference the interface.

2019-01-31 05:44 UTC, TristonianJones commented on cel/options.go
> +type EnvOption func(e *env) (*env, error)
I've opted to make the `EnvOption` implementations public, but make it impossible (for now) for external users to create their own. Perhaps in the future I'll open up this functionality.

2019-01-31 05:45 UTC, TristonianJones commented
PTAL

2019-02-01 22:40 UTC, JimLarson requested changes

2019-02-01 22:40 UTC, JimLarson commented on README.md
> +	if iss != nil && iss.Err() {
Should be `iss.Err() != nil` here too.

2019-02-01 22:40 UTC, JimLarson commented on README.md
> +	if iss != nil && iss.Err() {
Should be `iss.Err() != nil`.
Meta: audit against the test code.

2019-02-01 22:40 UTC, JimLarson commented on cel/cel.go
> +// Copyright 2018 Google LLC
s/2018/2019/ for newly-created files?

2019-02-01 22:40 UTC, JimLarson commented on cel/cel_test.go
> +	prg, _ := e.Program(c, funcs, Globals(Vars(map[string]interface{}{
Add a comment to emphasize:
// Global variables can be set in the Program and optionally overriden in Eval.

2019-02-01 22:40 UTC, JimLarson commented on cel/cel_test.go
> +	// Test to see whether 'v != false' was resolved to a value.
Test that both sides were evaluated - these tests shouldn't depend on whether we evaluate lhs or rhs first.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	// Macros and the standard built-ins are enabled by default.
Move this to the external description.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	Metadata() *exprpb.SourceInfo
Not happy with the name, since it doesn't abstract over its return type. I'd say change it to SourceInfo(), but you could instead have it return a new Metadata type that abstracts SourceInfo.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	// ResultType returns the output type of the expression, or error if the IsChecked() == false.
Consider returning Dyn if IsChecked() == false - I'll bet the behavior for checked && Dyn would be the same for unchecked in all cases, so don't make every caller implement this logic.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	// Parse parses the input txt to a Ast and/or a set of Issues.
Be clear that "input" means a CEL expression.

2019-02-01 22:40 UTC, JimLarson commented on cel/options.go
> +type EnvOption func(e *env) (*env, error)
My point is that if you might want to drop the `*env` from the return type if it's never going to be different than what is passed in.

Sometimes you might want to return one of your unmodified arguments for a "builder" pattern:
```
foo := NewFooBuilder().SetName("bar").SetLevel(7).Build()
```
but here returning a pair with `error` prevents that, and it looks like you're going to varargs the options rather than chain them.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	Parse(txt string) (Ast, Issues)
Add options for parse.  For instance, source location and syntax version.

2019-02-01 22:40 UTC, JimLarson commented on cel/options.go
> +// Package sets the container for resolving variable names. Defaults to an empty package.
Rename to "Container".  Or declare that we'll standardize on "Package" and rename "Container" to "Package" in our protos, etc.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	// Parsing has failed if the returned Issues value and its Issues.Err() value is non-nil.
Note that a non-nil Ast might be returned even in the case of a parsing error, in the hope that partial results might be useful, but the returned Ast is not necessarily valid for use in later phases in this case.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	// Checking has failed if the returned Issues value and its Issues.Err() value is non-nil.
Note that a non-nil Ast might be returned even in the case of a check error, in the hope that partial results might be useful, but the returned Ast is not necessarily valid for use in later phases in this case.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	return &astValue{
How about using ParsedExprToAst here?

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	return &astValue{
How about using CheckedExprToAst here?

2019-02-01 22:40 UTC, JimLarson commented on cel/cel_test.go
> +func Test_ExampleWithBuiltins(t *testing.T) {
Review the use of "builtin" in the API:  we seem to be using it both for the set of all built-in identifiers and macros, and for extension functions added to the run-time.  These should be distinct concepts with distinct names.

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +	// MacroKey returns the macro signatures accepted by this macro.
Give a reference to the notation for "macro signature".

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +		// The macro "range.all(var, predicate)", which is true if for all elements in range the
We had discussed limiting "comprehensions" to operating on lists only, making the map-key-to-list conversion explicit and deterministic.

2019-02-01 22:40 UTC, JimLarson commented on cel/env.go
> +	Source() common.Source
Here and below:  so this makes common.Source part of the public API.  Other API methods also return types outside of the cel package.  Do we want to eventually make this API self-contained?

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +	// ArgCount for the function call.
Explain what this returns for VarArg macros.

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +// IsInstanceStyle returns whether the macro is "instance" (reciever) style.
s/Instance/Receiver/

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +	// - iterRange represents the expression that resolves to a list or map where the elements or
Again, need to decide whether to continue direct support for maps.

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +	// - accuVar is the accumulation variable name, typically parser.AccumulatorName.
Explain constraints on this.  For instance, it shouldn't shadow a variable that you want to access from step or condition.

2019-02-01 22:40 UTC, JimLarson commented on parser/macro.go
> +	// GlobalCall creates a function call Expr value for a global (free) function.
Meh, the member calls are global too.  How about just plain Call() and MemberCall() (or even better, ReceiverCall())?

2019-02-01 23:29 UTC, TristonianJones commented on cel/env.go
> +	Metadata() *exprpb.SourceInfo
Changed to `SourceInfo`.

2019-02-01 23:38 UTC, TristonianJones commented on cel/env.go
> +	// ResultType returns the output type of the expression, or error if the IsChecked() == false.
Good suggestion.

2019-02-01 23:46 UTC, TristonianJones commented on cel/env.go
> +	Parse(txt string) (Ast, Issues)
The functional option pattern within Go seems to be pretty common. When multiple versions are supported, we should be able to add a `type SourceOption func(cel.Source) (cel.Source, err)` as a variadic argument to the `Parse` call.  I've added a top-level `cel.Source` wrapper around `common.Source` in order to permit this sort of feature in the future.

2019-02-01 23:57 UTC, TristonianJones commented on cel/env.go
> +	return &astValue{
Added a comment about why not, but I did use `AstToParsedExpr` within the `Check`

2019-02-01 23:58 UTC, TristonianJones commented on cel/env.go
> +	return &astValue{
Added a comment about why not, but very reasonable suggestion.

2019-02-01 23:59 UTC, TristonianJones commented on cel/cel_test.go
> +func Test_ExampleWithBuiltins(t *testing.T) {
This is actually using the builtin operators to perform the same operation as the `Test_Example` does, rather than using extension functions.

2019-02-01 23:59 UTC, TristonianJones commented on cel/env.go
> +	Source() common.Source
I created a top-level wrapper for `cel.Source` and opted for it instead.

2019-02-02 00:01 UTC, TristonianJones commented on parser/macro.go
> +		// The macro "range.all(var, predicate)", which is true if for all elements in range the
Folks are already using `map` values as input to these comprehensions, so I think we can improve how they function, but can't remove the feature in the short-term.

2019-02-02 00:16 UTC, TristonianJones commented
Thanks for the review PTAL.

2019-02-04 22:59 UTC, JimLarson approved these changes

2019-02-04 23:30 UTC, merged