Add an option to disable aggregates with dynamic element types.
cel-expr/cel-go pull request #183
Opened 2019-03-13 16:59 UTC by TristonianJones

This pull closes feature request #144 and will allow users to disable support for aggregate literals with mixed element types. This feature can be enabled via the following top-level option:
```go
env, err := cel.NewEnv(cel.HomogeneousAggregateLiterals())
```

2019-03-13 17:29 UTC, glerchundi commented
Thanks for making this happen @TristonianJones! 👏

2019-03-13 18:32 UTC, TristonianJones commented
You're very welcome, this has come up in a couple of different venues, so I'm glad you'll be putting it to good use.

2019-03-21 00:54 UTC, JimLarson requested changes
Clarify in doc comments that it's a check-time only option - or add a TODO if you're going to add a runtime restriction.

2019-03-21 17:51 UTC, TristonianJones commented
This is a check-time only restriction. It's still possible to have heterogeneous aggregates at runtime and when using unchecked expressions.

2019-03-21 18:45 UTC, JimLarson approved these changes

2019-03-21 18:45 UTC, JimLarson commented on cel/options.go
> +// expression or with unchecked expressions.
...or via implicit conversion from well-known types.

2019-03-21 21:47 UTC, merged