Update the README.md with clearer getting started guidance.
cel-expr/cel-go pull request #188
Opened 2019-03-17 08:03 UTC by TristonianJones

2019-03-18 22:15 UTC, JimLarson requested changes

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +The Common Expression Language (CEL) is a non-Turing complete language designed
Hyperlink to the cel-spec README.md ASAP.  What's here should summarize the high points of that document - in particular, there should be no new content here that applies to CEL in general, such as the examples below.

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +```javascript
This example suggests that we support sequences of expressions - separate these as different displayed block, i.e. each has its own triple-single-quote start/end.

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +Let's expose `resource.name` and  `auth.claims` variables to CEL using the
I don't like encouraging people to use qualified identifiers.  Could you make the example simpler?

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +`auth.claims` could originate from a JSON Web Token (JWT).
Use of JWT seems pretty wild for first basic example.

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +`dyn` values. The `dyn` in this case represents JSON input as the
Dislike introducing 'dyn' and explaining only what it means in this case.

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +When some of the input is unknown, the `out` value will contain a list of the
...when some input is bound to a special "Unknown" value.  Current behavior is a bug and shouldn't be documented.

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +CEL evaluates very quickly. When the expression set does not change frequently,
delete "set"

2019-03-18 22:15 UTC, JimLarson commented on README.md
> +CEL evaluates linearly with respect to the size of the expression and the input
...if macros are disabled.

2019-03-19 14:57 UTC, TristonianJones commented on README.md
> +The Common Expression Language (CEL) is a non-Turing complete language designed
Linked on "syntax". I'll follow up with the cel-spec to revise the high-level content there as well.

2019-03-19 14:57 UTC, TristonianJones commented on README.md
> +```javascript
I've split the example apart and added a comment that a CEL "program" is a single expression.

2019-03-19 14:57 UTC, TristonianJones commented on README.md
> +Let's expose `resource.name` and  `auth.claims` variables to CEL using the
I switched to primitive types

2019-03-19 14:57 UTC, TristonianJones commented on README.md
> +`auth.claims` could originate from a JSON Web Token (JWT).
I made this less JWT specific.

2019-03-21 01:37 UTC, JimLarson approved these changes
A few comments, but looks much better.

2019-03-21 01:37 UTC, JimLarson commented on README.md
> +Determine the attribute names and functions you want to provide to the CEL
"Variable names" instead of "attribute names".  Attributes refer to properties of an underlying entity.

2019-03-21 01:37 UTC, JimLarson commented on README.md
> +Let's expose `name` and  `group` variables to CEL using the standard builtins:
...using the "Declarations" option.

2019-03-21 04:15 UTC, sefk approved these changes
This is a great improvement over what we had already, thanks for adding Tristan!

2019-03-21 04:15 UTC, sefk commented on README.md
> +Macros are enabled by default and may be disabled. The comprehension macros
I've always found macros to be one of the more confusing aspects of CEL. Why are they different than just any other language feature? Why are they called that? I confess that I tried to see how I'd explain and wasn't sure I could.

2019-03-21 05:28 UTC, merged