Fix namespaced function resolution
cel-expr/cel-go pull request #341
Opened 2020-04-22 16:26 UTC by TristonianJones

Type checking correctly resolves namespaced function names like `base64.encode`; however, this information was being lost at evaluation time with the fragment `base64` being treated as a variable name and `encode` as the function name.

This PR fixes the glitch for namespaced function resolution ensuring the evaluator honors the CEL program container name and qualified function names.

2020-04-23 22:25 UTC, TristonianJones commented
@JimLarson PTAL, the PR now introduces AST rewrites at Check time to drop / consolidate parse-time AST fragments in favor of ASTs that more accurately represent the eval intent.

2020-04-28 05:25 UTC, TristonianJones commented
PTAL whenever you have a chance @JimLarson. Thanks.

2020-05-01 08:16 UTC, JimLarson requested changes

2020-05-01 08:16 UTC, JimLarson commented on interpreter/planner.go
> +func (p *planner) toQualifiedName(operand *exprpb.Expr) (string, bool) {
Doc comment, please.

2020-05-01 08:16 UTC, JimLarson commented on checker/checker.go
>  			}
Note on the "else" path that we do not allow qualified names for receiver-style functions, so for `a.b.c()` either `a.b.c` is a function, or `c` is a function with target `a.b`, but it's never the case that `b.c` is a function with target `a`.

2020-05-01 08:16 UTC, JimLarson commented on checker/checker.go
> +		e.ExprKind = &exprpb.Expr_IdentExpr{
Comment "Rewrite the node to include the resolved fully-qualified variable name."

Since it's already an Expr_Ident node, can't we just overwrite the Name field?

2020-05-01 08:16 UTC, JimLarson commented on checker/checker.go
> +				e.ExprKind = &exprpb.Expr_IdentExpr{
Comment "Rewrite the node to be a variable reference to the resolved fully-qualified variable name."

2020-05-01 08:16 UTC, JimLarson commented on checker/checker.go
> +			call.Function = fn.Name
Comment "Overwrite with fully-qualified resolved function name".

2020-05-01 08:16 UTC, JimLarson commented on checker/checker.go
> +				call.Function = fn.GetName()
Be consistent with `fn.GetName()` vs `fn.Name` above.

2020-05-01 08:16 UTC, JimLarson commented on interpreter/planner.go
> +	typeName, defined := p.resolveTypeName(obj.MessageName)
So this all looks okay, but it's largely duplicating the logic in the checker.  I would much rather see the planner and the checker both call a separate pass of walking the AST to do the qualified identifier rewrites, with a pluggable qualified name tester that checks either declarations (checker) or bound variables and dispatchable functions (planner).  Yet another function can rewrite a CheckedExpr based on its reference map, returning early if it sees that the rewrite has already been performed.

Oh, nasty thought - can the iteration variable in a comprehension (fold) be a qualified name?  What if we are in container "a.b" and write `mylist.exists(a.b.c, c % 2 == 0)`?

2020-05-04 14:46 UTC, TristonianJones commented on interpreter/planner.go
> +	typeName, defined := p.resolveTypeName(obj.MessageName)
The comprehensions aren't permitted to have a qualified iteration variable (thank goodness). 

I've restructured the name qualification code to be right next to the `packager`, but it's a bit painful to disentangle the rest into a common unit. I could do as you suggest, but it seems easier to understand the similarities and differences by mirroring the conventions used in each file. At any rate, let me know what you think of the latest update.

2020-05-06 04:24 UTC, JimLarson approved these changes

2020-05-06 04:24 UTC, JimLarson commented on checker/checker.go
> +	// Rewrite the identifier to its fully qualified name.
Consider putting this comment at line 150, in the block where we're actually doing this rewrite.

2020-05-06 04:24 UTC, JimLarson commented on checker/checker.go
> +		call.Function = fn.GetName()
Comment "Overwrite function name with fully-qualified resolved name."

2020-05-06 13:34 UTC, merged