Fix unquoting when using single quote versus double.
cel-expr/cel-go pull request #38
Opened 2018-05-25 16:00 UTC by TristonianJones

The default `strings.unquote` strategy is to treat single quotes as characters
and double quotes as strings. CEL treats the two as synonymous. This commit
introduces a fallback scenario to handle errors related to single quoting.

2018-05-31 17:54 UTC, JimLarson commented on parser/parser.go
> +	}
Add comments for whatever remains to be done for string parsing, e.g. escapes, raw strings, triple-quoted, etc.

Add a unit test in parser_test.

2018-06-01 17:28 UTC, TristonianJones reviewed
I've updated the escaping logic to match that supported by Google SQL. The grammar itself does not yet support all that is in the implementation, so I've added a TODO. 

Note, I think there's a bug in cel-spec with one of the examples. \314\277 (as opposed to (\303\277) decodes to the example Ì¿

2018-06-03 23:55 UTC, JimLarson requested changes

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape_test.go
> +	text, err := unescape(`"\\\""`)
Add an explicit comment that the argument the unescape is the four-character string dquote-backslash-dquote-dquote.  (Though this is redundant, strictly speaking, we'll be pushing the corners of the host languages string literals, so the explicit comment will be valuable to the reader and for debugging.)

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape_test.go
> +	text, err := unescape(`"\314\277"`)
Add an explicit comment that:
octal 314 -> decimal 204 -> Latin Capital Letter I With Grave
octal 277 -> decimal 191 -> Inverted Question Mark
Also, see fix to langdef.md, example should be octal 303 -> decimal 191 -> &Atilde; to be the same values as the UTF-8 bytes for unicode 255.

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape.go
> +		return value, nil
This appears to recognize
r""ABC""
as
ABC
which doesn't match the CEL or Google SQL spec.  It should recognize either one- or three-quote strings.

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape.go
> +func unescapeChar(s string) (value rune, multibyte bool, tail string, err error) {
Add function comment explaining especially the meaning of the return values.

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape.go
> +	return
I'd prefer to see the explicit values in the return.

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape.go
> +	case 'x', 'u', 'U':
Google SQL also allows \Xhh, with the same meaning as \xhh.  Make a TODO/bug somewhere to update the CEL langdef.

2018-06-03 23:55 UTC, JimLarson commented on parser/unescape.go
> +			// single-byte string, possibly not UTF-8
The way I read the Google SQL spec, the hex and octal escapes name Unicode code points for strings, but byte values for bytes.  So the code is okay, but the comment seems wrong.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape.go
> +	case 'x', 'u', 'U':
There's a TODO listed in the CEL.g4 grammar to make the lexis Google SQL compatible, but it doesn't mention the specific changes. I'll file a GitHub issue with more details. In the mean time I've added 'X' to this block.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape.go
> +			// single-byte string, possibly not UTF-8
This comment comes from the the `strconv/quote.go` implementation. I'm not entirely sure why it's listed this way, though GoogleSQL does seem to instead always treat this value as a possibly being multibyte, so I've removed the block.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape.go
> +	return
Sure, happy to.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape_test.go
> +	text, err := unescape(`"\\\""`)
Done.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape_test.go
> +	text, err := unescape(`"\314\277"`)
Yes, my example changed to match the documented output. I can change it back to 303.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape.go
> +func unescapeChar(s string) (value rune, multibyte bool, tail string, err error) {
Done.

2018-06-04 19:55 UTC, TristonianJones commented on parser/unescape.go
> +		return value, nil
You're quite right. The CEL.g4 grammar only recognizes one or three, I've added a check to ensure odd-quoting.

2018-06-04 23:23 UTC, JimLarson approved these changes

2018-06-04 23:23 UTC, JimLarson commented on parser/unescape.go
> +//   multibyte - whether the rune value might require multiple bytes to represent.
s/might require/requires/

2018-06-04 23:23 UTC, JimLarson commented on parser/unescape.go
> +)
No newline at end of file.

2018-06-05 16:27 UTC, merged